from typing import Any

from django.utils.translation import gettext_lazy as _

JAZZMIN_SETTINGS: dict[str | Any, str | None | Any] = {
    "site_title": "classcom.uz",
    "site_header": "classcom.uz",
    "site_brand": "classcom.uz",
    "site_logo": "/images/classcom.png",
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "site_icon": None,
    "welcome_sign": _("classcom.uz ga xush kelibsiz"),
    "copyright": "classcom.uz Ltd",
    "search_model": ["auth.User"],
    "user_avatar": None,
    "topmenu_links": [
        {
            "name": _("Bosh sahifa"),
            "url": "admin:index",
            "permissions": ["auth.view_user"],
        },
        {
            "name": "classcom.uz",
            "url": "https://classcom.uz",
            "new_window": True,
        },
        {"model": "auth.User"},
        {"app": "books"},
    ],
    "usermenu_links": [
        # {
        #     "name": "Support",
        #     "url": "https://github.com/farridav/django-jazzmin/issues",
        #     "new_window": True,
        # },
        {"model": "auth.user"},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "books", "books.author", "books.book"],
    "custom_links": {
        "books": [
            {
                "name": "Make Messages",
                "url": "make_messages",
                "icon": "fas fa-comments",
                "permissions": ["books.view_book"],
            }
        ]
    },
    "icons": {
        "http.Comment": "fas fa-comments",
        "http.FrontendTranslation": "fas fa-globe",
        "http.Post": "fas fa-bars",
        "http.User": "fas fa-user",
        "http.Tags": "fas fa-tag",
        "http.SmsConfirm": "fas fa-comments",
        "http.District": "fas fa-map-marker",
        "http.Region": "fas fa-map-marker",
        "http.ScienceGroups": "fas fa-flask",
        "http.SchoolType": "fas fa-school",
        "auth.Group": "fas fa-users",
        "auth.Permission": "fas fa-key",
        "classcom.Answer": "fas fa-check",
        "classcom.Classes": "fas fa-school",
        "classcom.DaysOff": "fas fa-calendar",
        "classcom.Download": "fas fa-download",
        "classcom.Feedback": "fas fa-comments",
        "classcom.Media": "fas fa-image",
        "classcom.Moderator": "fas fa-user-shield",
        "classcom.Notification": "fas fa-bell",
        "classcom.Plan": "fas fa-calendar",
        "classcom.Quarter": "fas fa-calendar",
        "classcom.Resource": "fas fa-book",
        "classcom.Schedule": "fas fa-calendar",
        "classcom.Science": "fas fa-flask",
        "classcom.Settings": "fas fa-cogs",
        "classcom.Teacher": "fas fa-chalkboard-teacher",
        "classcom.Topic": "fas fa-book",
        "classcom.ScienceTypes": "fas fa-flask",
        "classcom.Category": "fas fa-list",
        "classcom.CategoryType": "fas fa-list",
        "classcom.ResourceType": "fas fa-list",
        "classcom.ClassType": "fas fa-school",
        "classcom.TempModerator": "fas fa-user-shield",
        "classcom.Chat": "fas fa-comments",
        "classcom.ScheduleChoices": "fas fa-calendar",
        "classcom.Weeks": "fas fa-calendar",
        "payments.Payments": "fas fa-money-bill",
        "payments.Orders": "fas fa-shopping-cart",
        "payments.Plans": "fas fa-calendar",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_css": "css/jazzmin.css",
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "auth.group": "vertical_tabs",
    },
    "language_chooser": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": True,
    "brand_small_text": False,
    "brand_colour": "navbar-navy",
    "accent": "accent-primary",
    "navbar": "navbar-navy navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-navy",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "minty",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-outline-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
    "actions_sticky_top": False,
}
