# Generated by Django 5.0.4 on 2024-04-29 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_feedback_answer"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="user",
        ),
        migrations.DeleteModel(
            name="Answer",
        ),
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
