# Generated by Django 5.1 on 2024-08-19 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0003_remove_feedback_user_delete_answer_delete_feedback",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resettoken",
            options={
                "verbose_name": "Tokenni tiklash",
                "verbose_name_plural": "Tokenni tiklash",
            },
        ),
        migrations.AlterField(
            model_name="resettoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="resettoken",
            name="token",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Token"
            ),
        ),
        migrations.AlterField(
            model_name="resettoken",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="resettoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
    ]
