# Generated by Django 5.0.8 on 2024-08-30 10:06

import core.apps.classcom.models.schedule
import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(1000)
                        ],
                        verbose_name="Javob",
                    ),
                ),
            ],
            options={
                "verbose_name": "Javob",
                "verbose_name_plural": "Javoblar",
                "db_table": "answer",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Kategoriya nomi"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Kategoriya nomi",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Kategoriya nomi",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Kategoriya nomi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Kategoriya turi"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Kategoriya turi",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Kategoriya turi",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Kategoriya turi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kategoriya turi",
                "verbose_name_plural": "Kategoriyalar turi",
            },
        ),
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("massage", models.TextField(verbose_name="Xabar")),
                (
                    "time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Vaqt"
                    ),
                ),
                (
                    "response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Javob"
                    ),
                ),
                (
                    "response_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Javob vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat",
                "verbose_name_plural": "Chatlar",
            },
        ),
        migrations.CreateModel(
            name="Classes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Sinf nomi"),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Sinf nomi"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Sinf nomi"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Sinf nomi"
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tartib raqami"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sinf",
                "verbose_name_plural": "Sinflar",
                "ordering": ("order_number",),
            },
        ),
        migrations.CreateModel(
            name="ClassType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Sinf guruhi nomi"
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Sinf guruhi nomi",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Sinf guruhi nomi",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255,
                        null=True,
                        verbose_name="Sinf guruhi nomi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sinf Guruhi",
                "verbose_name_plural": "Sinf Guruhlari",
            },
        ),
        migrations.CreateModel(
            name="DaysOff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "from_date",
                    models.DateField(verbose_name="Boshlang'ich sana"),
                ),
                ("to_date", models.DateField(verbose_name="Oxirgi sana")),
                (
                    "reason",
                    models.CharField(max_length=255, verbose_name="Sababi"),
                ),
            ],
            options={
                "verbose_name": "Dam olish kuni",
                "verbose_name_plural": "Dam olish kunlari",
                "db_table": "days_off",
            },
        ),
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("date", models.DateField(verbose_name="Sanasi")),
            ],
            options={
                "verbose_name": "Yuklamalar",
                "verbose_name_plural": "Yuklamalar",
            },
        ),
        migrations.CreateModel(
            name="DownloadToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="Token",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="Muddati")),
            ],
            options={
                "verbose_name": "Yuklash uchun token",
                "verbose_name_plural": "Yuklash uchun tokenlar",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[("first", "First"), ("second", "Second")],
                        max_length=10,
                        verbose_name="Feedback turi",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        validators=[
                            django.core.validators.MaxLengthValidator(1000)
                        ],
                        verbose_name="Mazmuni",
                    ),
                ),
                (
                    "answered",
                    models.BooleanField(
                        default=False, verbose_name="Javob berildimi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fikr-mulohaza",
                "verbose_name_plural": "Fikr-mulohazalar",
                "db_table": "feedback",
            },
        ),
        migrations.CreateModel(
            name="LanguageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                        max_length=2,
                        verbose_name="Til",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nomi",
                    ),
                ),
                (
                    "name_uz",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nomi",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nomi",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nomi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Til",
                "verbose_name_plural": "Tillar",
            },
        ),
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nomi",
                    ),
                ),
                (
                    "desc",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tavsif"
                    ),
                ),
                (
                    "desc_uz",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tavsif"
                    ),
                ),
                (
                    "desc_ru",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tavsif"
                    ),
                ),
                (
                    "desc_en",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tavsif"
                    ),
                ),
                (
                    "file",
                    models.FileField(upload_to="media/", verbose_name="Fayl"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Fayl turi",
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, default=0, null=True, verbose_name="Hajmi"
                    ),
                ),
                (
                    "count",
                    models.IntegerField(
                        default=0, verbose_name="Yuklashlar soni"
                    ),
                ),
                (
                    "statistics",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Statistika",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Medialar",
            },
        ),
        migrations.CreateModel(
            name="Moderator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "balance",
                    models.BigIntegerField(default=0, verbose_name="Balans"),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("HIGHER", "Oliy toifa"),
                            ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                            (
                                "GOOD_TEACHER",
                                "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                            ),
                            ("AUTHOR", "Darslik muallifi"),
                        ],
                        default="AUTHOR",
                        max_length=15,
                        verbose_name="Daraja",
                    ),
                ),
                (
                    "docs",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="Hujjat",
                    ),
                ),
                (
                    "is_contracted",
                    models.BooleanField(
                        default=False, verbose_name="Shartnoma"
                    ),
                ),
                (
                    "plan_creatable",
                    models.BooleanField(
                        default=False,
                        verbose_name="Tematik Reja yarata olishi",
                    ),
                ),
                (
                    "resource_creatable",
                    models.BooleanField(
                        default=False, verbose_name="Resurs yarata olishi."
                    ),
                ),
                (
                    "topic_creatable",
                    models.BooleanField(
                        default=False, verbose_name="Mavzu yarata olishi."
                    ),
                ),
            ],
            options={
                "verbose_name": "Moderator",
                "verbose_name_plural": "Moderatorlar",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Faol"),
                ),
                (
                    "hour",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Soat"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                        default="uz",
                        max_length=2,
                        verbose_name="Til",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tematik reja",
                "verbose_name_plural": "Tematik rejalar",
            },
        ),
        migrations.CreateModel(
            name="Quarter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "choices",
                    models.IntegerField(
                        choices=[
                            (1, "First Quarter"),
                            (2, "Second Quarter"),
                            (3, "Third Quarter"),
                            (4, "Fourth Quarter"),
                        ],
                        default=1,
                        verbose_name="Chorak",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.today,
                        verbose_name="Boshlang'ich sana",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime.today,
                        verbose_name="Oxirgi sana",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chorak",
                "verbose_name_plural": "Choraklar",
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nomi"),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                ("description", models.TextField(verbose_name="Tavsif")),
                (
                    "description_uz",
                    models.TextField(null=True, verbose_name="Tavsif"),
                ),
                (
                    "description_ru",
                    models.TextField(null=True, verbose_name="Tavsif"),
                ),
                (
                    "description_en",
                    models.TextField(null=True, verbose_name="Tavsif"),
                ),
                (
                    "banner",
                    models.ImageField(
                        upload_to="resource_banners/", verbose_name="Banner"
                    ),
                ),
                (
                    "subtype",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Resurs sub turi",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Manba",
                    ),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("LOW", "Past"),
                            ("MEDIUM", "O'rta"),
                            ("HIGH", "Yuqori"),
                        ],
                        default="MEDIUM",
                        verbose_name="Daraja",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tartib raqami"
                    ),
                ),
            ],
            options={
                "verbose_name": "Resurs",
                "verbose_name_plural": "Resurslar",
                "ordering": ["order_number"],
            },
        ),
        migrations.CreateModel(
            name="ResourceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nomi"),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("BYLIST", "By list"),
                            ("BYCLASS", "By class"),
                            ("BYCLASSANDUNIT", "By class and unit"),
                            ("BYDEPARTMENT", "By Department"),
                            ("BYDOCS", "By docs"),
                            ("BYSCHOOL", "By school"),
                            ("BYSCIENCE", "By science"),
                        ],
                        max_length=255,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktiv"),
                ),
            ],
            options={
                "verbose_name": "Resurs turi",
                "verbose_name_plural": "Resurs turlari",
                "ordering": ["order_number"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Ertalabki"),
                            ("EVENING", "Kechki"),
                        ],
                        default="MORNING",
                        max_length=255,
                        verbose_name="Smena",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("monday", "Dushanba"),
                            ("tuesday", "Seshanba"),
                            ("wednesday", "Chorshanba"),
                            ("thursday", "Payshanba"),
                            ("friday", "Juma"),
                            ("saturday", "Shanba"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="Kun",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(verbose_name="Boshlanish vaqti"),
                ),
                ("end_time", models.TimeField(verbose_name="Tugash vaqti")),
                (
                    "lesson_time",
                    models.CharField(
                        max_length=25,
                        validators=[
                            core.apps.classcom.models.schedule.validate_lesson_time
                        ],
                        verbose_name="Dars vaqti",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars jadvali",
                "verbose_name_plural": "Dars jadvali",
                "ordering": ["weekday", "lesson_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleChoices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars jadvali tanlash",
                "verbose_name_plural": "Dars jadvali tanlash",
            },
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dars jadval shablon nomi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dars jadval shabloni",
                "verbose_name_plural": "Dars jadval shabloni",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Science",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(verbose_name="Nomi")),
                ("name_uz", models.CharField(null=True, verbose_name="Nomi")),
                ("name_ru", models.CharField(null=True, verbose_name="Nomi")),
                ("name_en", models.CharField(null=True, verbose_name="Nomi")),
                (
                    "order_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tartib raqami"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
                "ordering": ["order_number"],
            },
        ),
        migrations.CreateModel(
            name="ScienceTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                ("name", models.CharField(verbose_name="Nomi")),
                ("name_uz", models.CharField(null=True, verbose_name="Nomi")),
                ("name_ru", models.CharField(null=True, verbose_name="Nomi")),
                ("name_en", models.CharField(null=True, verbose_name="Nomi")),
            ],
            options={
                "verbose_name": "Fan turi",
                "verbose_name_plural": "Fan turlari",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Key"
                    ),
                ),
                ("value", models.TextField(verbose_name="Qiymati")),
            ],
            options={
                "verbose_name": "Sozlamalar",
                "verbose_name_plural": "Sozlamalar",
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "payment_status",
                    models.BooleanField(
                        default=False, verbose_name="To'lov holati"
                    ),
                ),
            ],
            options={
                "verbose_name": "O'qituvchi",
                "verbose_name_plural": "O'qituvchilar",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="TempModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "balance",
                    models.BigIntegerField(default=0, verbose_name="Balans"),
                ),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("HIGHER", "Oliy toifa"),
                            ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                            (
                                "GOOD_TEACHER",
                                "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                            ),
                            ("AUTHOR", "Darslik muallifi"),
                        ],
                        default="AUTHOR",
                        max_length=15,
                        verbose_name="Daraja",
                    ),
                ),
                (
                    "docs",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="documents/",
                        verbose_name="Hujjat",
                    ),
                ),
                (
                    "is_contracted",
                    models.BooleanField(
                        default=False, verbose_name="Shartnoma"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Nomi"),
                ),
                (
                    "name_uz",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Nomi"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tavsif"
                    ),
                ),
                (
                    "sequence_number",
                    models.IntegerField(
                        default=1, verbose_name="Tartib raqami"
                    ),
                ),
                (
                    "hours",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Soatlar"
                    ),
                ),
                (
                    "media_creatable",
                    models.BooleanField(
                        default=False, verbose_name="Media yarata olishi."
                    ),
                ),
                (
                    "weeks",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        null=True,
                        verbose_name="Haftalar",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
                "ordering": ["sequence_number"],
            },
        ),
        migrations.CreateModel(
            name="Weeks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "week_count",
                    models.IntegerField(verbose_name="Hafta raqami"),
                ),
                (
                    "start_date",
                    models.DateField(
                        verbose_name="Haftaning boshlanish sanasi"
                    ),
                ),
                (
                    "end_date",
                    models.DateField(verbose_name="Haftaning tugash sanasi"),
                ),
            ],
            options={
                "verbose_name": "Hafta",
                "verbose_name_plural": "Haftalar",
            },
        ),
    ]
