# Generated by Django 5.0.6 on 2024-06-29 05:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="thematic_plan",
        ),
        migrations.AddField(
            model_name="topic",
            name="thematic_plan",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="topics",
                to="classcom.plan",
            ),
        ),
    ]
