# Generated by Django 5.0.6 on 2024-06-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0002_remove_topic_thematic_plan_topic_thematic_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="science",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="science",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
