# Generated by Django 5.0.4 on 2024-04-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcom', '0002_remove_resource_moderator_resource_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='size',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
