# Generated by Django 5.0.8 on 2024-08-30 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
    ]
