# Generated by Django 5.0.6 on 2024-07-02 06:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0003_science_created_at_science_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="created_at",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
