# Generated by Django 5.0.4 on 2024-04-26 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcom', '0003_alter_schedule_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='date',
            new_name='weekday',
        ),
    ]
