# Generated by Django 5.0.8 on 2024-09-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0003_resource_science"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="name_uz",
        ),
    ]
