# Generated by Django 5.0.8 on 2024-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0004_remove_topic_name_en_remove_topic_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Title"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Description"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/", verbose_name="File"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Is active"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Type",
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, default=0, null=True, verbose_name="Size"
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                max_length=2,
                unique=True,
                verbose_name="Til",
            ),
        ),
        migrations.RemoveField(
            model_name="moderator",
            name="docs",
        ),
        migrations.AddField(
            model_name="moderator",
            name="docs",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderators",
                to="classcom.document",
                verbose_name="Hujjatlar",
            ),
        ),
    ]
