# Generated by Django 5.0.4 on 2024-04-27 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcom', '0004_rename_date_schedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderator',
            name='docs',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
