# Generated by Django 5.0.8 on 2024-09-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0004_chat_is_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai",
            name="type",
            field=models.CharField(
                choices=[("ALL", "Barchasi"), ("TOPIC", "Mavzuga qarab")],
                default=1,
                max_length=255,
                verbose_name="Turi",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ai",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ais",
                to="classcom.topic",
                verbose_name="Mavzu",
            ),
        ),
    ]
