# Generated by Django 5.0.7 on 2024-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0005_remove_resource_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="classes",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="classes",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="desc_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="desc_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="desc_uz",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="name_ru",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="media",
            name="name_uz",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="message_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="description_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="description_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="description_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="science",
            name="name_en",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="science",
            name="name_ru",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="science",
            name="name_uz",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
