# Generated by Django 5.0.4 on 2024-04-27 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcom', '0005_alter_moderator_docs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classcom.download')),
            ],
        ),
    ]
