# Generated by Django 5.0.7 on 2024-07-24 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0005_remove_resource_topic"),
        ("http", "0011_alter_user_district_alter_user_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="science",
            name="science_grp",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="http.sciencegroups",
            ),
        ),
    ]
