# Generated by Django 5.0.8 on 2024-09-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0005_ai_type_alter_ai_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ai",
            options={
                "ordering": ["-id"],
                "verbose_name": "Suniy Intellekt",
                "verbose_name_plural": "Suniy Intellektlar",
            },
        ),
    ]
