# Generated by Django 5.0.8 on 2024-09-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0006_alter_ai_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="is_contracted",
            field=models.BooleanField(
                default=False, verbose_name="Tasdiqlash"
            ),
        ),
    ]
