# Generated by Django 5.0.8 on 2024-09-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0006_alter_document_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "verbose_name": "Hujjat",
                "verbose_name_plural": "Hujjatlar",
            },
        ),
        migrations.AlterField(
            model_name="document",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tasnifi"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                upload_to="documents/%Y/%m/%d/", verbose_name="Fayl"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Holati"),
        ),
        migrations.AlterField(
            model_name="document",
            name="size",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="Hajmi"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="document",
            name="type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Turi"
            ),
        ),
    ]
