# Generated by Django 5.0.7 on 2024-07-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0006_science_science_grp"),
        (
            "classcom",
            "0007_alter_plan_plan_resource_alter_topic_thematic_plan",
        ),
    ]

    operations = []
