# Generated by Django 5.0.8 on 2024-09-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0007_alter_moderator_is_contracted"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="status",
            field=models.BooleanField(
                default=False, verbose_name="Shartnoma statusi"
            ),
        ),
    ]
