# Generated by Django 5.0.4 on 2024-04-29 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classcom', '0007_rename_answered_feedback_is_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='is_answered',
            new_name='nswered',
        ),
    ]
