# Generated by Django 5.0.8 on 2024-09-07 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0008_download_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="download",
            name="moderator",
        ),
        migrations.RemoveField(
            model_name="download",
            name="teacher",
        ),
    ]
