# Generated by Django 5.0.7 on 2024-07-31 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0008_merge_20240725_1739"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TempModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance", models.BigIntegerField(default=0)),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("HIGHER", "Oliy toifa"),
                            ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                            (
                                "GOOD_TEACHER",
                                "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                            ),
                            ("AUTHOR", "Darslik muallifi"),
                        ],
                        default="AUTHOR",
                        max_length=15,
                    ),
                ),
                (
                    "docs",
                    models.FileField(
                        blank=True, null=True, upload_to="documents/"
                    ),
                ),
                ("is_contracted", models.BooleanField(default=False)),
                (
                    "classes",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classcom.classes",
                    ),
                ),
                (
                    "science",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="classcom.science",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
