# Generated by Django 5.0.4 on 2024-04-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0009_rename_nswered_feedback_answered"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
    ]
