# Generated by Django 5.0.8 on 2024-10-05 10:35

import core.apps.classcom.models.topic
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0009_alter_topic_media_creatable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="topic/banner/",
                verbose_name="Banner",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=core.apps.classcom.models.topic.default_user,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
    ]
