# Generated by Django 5.0.4 on 2024-04-29 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0007_daysoff"),
        ("classcom", "0010_notification_is_read"),
    ]

    operations = []
