# Generated by Django 5.0.7 on 2024-08-03 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0010_category_categorytype_resource_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorytype",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorytype",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="categorytype",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="resource",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.categorytype",
            ),
        ),
    ]
