# Generated by Django 5.0.8 on 2024-10-05 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0010_topic_banner_topic_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="view_count",
            field=models.PositiveBigIntegerField(
                default=0, verbose_name="Ko'rishlar soni"
            ),
        ),
    ]
