# Generated by Django 5.0.7 on 2024-08-03 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0011_category_name_en_category_name_ru_category_name_uz_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="category_type",
        ),
    ]
