# Generated by Django 5.0.7 on 2024-08-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0011_orders"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScienceTypes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name="orders",
            name="price",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orders",
            name="types",
            field=models.ManyToManyField(to="classcom.sciencetypes"),
        ),
        migrations.AddField(
            model_name="science",
            name="types",
            field=models.ManyToManyField(to="classcom.sciencetypes"),
        ),
    ]
