# Generated by Django 5.0.4 on 2024-04-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classcom', '0011_merge_0007_daysoff_0010_notification_is_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('first', 'First'), ('second', 'Second')], max_length=10),
        ),
    ]
