# Generated by Django 5.0.1 on 2024-09-12 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0011_remove_tempmoderator_science_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TempModerator",
        ),
    ]
