# Generated by Django 5.0.8 on 2024-10-07 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0012_alter_topic_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="topic",
        ),
        migrations.AddField(
            model_name="topic",
            name="plan",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topic",
                to="classcom.plan",
            ),
            preserve_default=False,
        ),
    ]
