# Generated by Django 5.0.7 on 2024-08-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0012_sciencetypes_orders_price_orders_types_science_types",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="status",
            field=models.BooleanField(default=False),
        ),
    ]
