# Generated by Django 5.0.6 on 2024-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0012_alter_feedback_feedback_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="description",
        ),
        migrations.RemoveField(
            model_name="media",
            name="title",
        ),
        migrations.AddField(
            model_name="resource",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="resource_banners/"
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
