# Generated by Django 5.0.7 on 2024-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0013_orders_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="start_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
