# Generated by Django 5.0.6 on 2024-06-05 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0013_remove_media_description_remove_media_title_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="resource",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.topic",
            ),
        ),
    ]
