# Generated by Django 5.0.8 on 2024-10-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0013_remove_plan_topic_topic_plan"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="plan",
            new_name="plan_id",
        ),
    ]
