# Generated by Django 5.0.8 on 2024-10-10 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0014_rename_plan_topic_plan_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="download",
            name="object_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Object ID"
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="type",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Yuklash turi",
            ),
        ),
    ]
