# Generated by Django 5.0.7 on 2024-08-05 11:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0012_remove_category_category_type"),
        ("classcom", "0014_alter_orders_end_date_alter_orders_start_date"),
    ]

    operations = []
