# Generated by Django 5.0.8 on 2024-10-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0015_download_object_id_download_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="object_type",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Object turi",
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="object_type_id",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Object turi ID"
            ),
        ),
    ]
