# Generated by Django 5.0.7 on 2024-08-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0015_merge_20240805_1600"),
    ]

    operations = [
        migrations.AddField(
            model_name="sciencetypes",
            name="name_en",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="sciencetypes",
            name="name_ru",
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name="sciencetypes",
            name="name_uz",
            field=models.CharField(null=True),
        ),
    ]
