# Generated by Django 5.0.6 on 2024-06-06 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0016_plan_banner_plan_description_plan_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="quarter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.quarter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="science",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.science",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="hour",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
