# Generated by Django 5.0.7 on 2024-08-05 12:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "classcom",
            "0016_sciencetypes_name_en_sciencetypes_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="Orders",
        ),
    ]
