# Generated by Django 5.0.8 on 2024-10-10 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0016_media_object_type_media_object_type_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="download",
            old_name="type",
            new_name="object_type",
        ),
    ]
