# Generated by Django 5.0.8 on 2024-08-07 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0017_delete_orders"),
        ("classcom", "0017_merge_20240805_1753"),
    ]

    operations = []
