# Generated by Django 5.0.6 on 2024-06-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0017_plan_quarter_plan_science_alter_plan_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="banner",
            field=models.ImageField(default=1, upload_to="plan/banner/"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resource",
            name="banner",
            field=models.ImageField(default=1, upload_to="resource_banners/"),
            preserve_default=False,
        ),
    ]
