
# Generated by Django 5.0.6 on 2024-06-08 13:38
from django.db import migrations, models
class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0018_alter_plan_banner_alter_plan_description_and_more"),
    ]
    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="plan_resource",
        ),
        migrations.AddField(
            model_name="plan",
            name="plan_resource",
            field=models.ManyToManyField(
                blank=True, null=True, to="classcom.media"
            ),
        ),
    ]