# Generated by Django 5.0.8 on 2024-10-11 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0018_rename_object_type_id_media_object_id"),
        ("http", "0008_user_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeModerator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("accepted", "Qabul qilindi"),
                            ("rejected", "Rad etildi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Holat",
                    ),
                ),
                (
                    "class_groups",
                    models.ManyToManyField(
                        blank=True,
                        to="http.classgroup",
                        verbose_name="Sinflar turlari",
                    ),
                ),
                (
                    "classes",
                    models.ManyToManyField(
                        blank=True,
                        to="classcom.classes",
                        verbose_name="Sinflar",
                    ),
                ),
                (
                    "science",
                    models.ManyToManyField(
                        blank=True, to="classcom.science", verbose_name="Fan"
                    ),
                ),
                (
                    "science_type",
                    models.ManyToManyField(
                        blank=True,
                        to="classcom.sciencetypes",
                        verbose_name="Fan turi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
