# Generated by Django 5.0.8 on 2024-10-11 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0019_changemoderator"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changemoderator",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Moderator o'zgartirish",
                "verbose_name_plural": "Moderator o'zgartirishlar",
            },
        ),
    ]
