# Generated by Django 5.0.6 on 2024-06-13 13:12

from django.db import migrations, models

import core.apps.classcom.models.schedule


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0019_remove_plan_plan_resource_plan_plan_resource"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="schedule",
            name="lesson_time",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[
                    core.apps.classcom.models.schedule.validate_lesson_time
                ],
            ),
        ),
    ]
