# Generated by Django 5.0.8 on 2024-08-07 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0019_remove_moderator_classes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moderator",
            name="science_group",
        ),
        migrations.RemoveField(
            model_name="tempmoderator",
            name="science_group",
        ),
        migrations.AddField(
            model_name="moderator",
            name="science_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.sciencetypes",
            ),
        ),
        migrations.AddField(
            model_name="tempmoderator",
            name="science_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.sciencetypes",
            ),
        ),
    ]
