# Generated by Django 5.0.6 on 2024-06-19 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0020_alter_plan_unique_together_schedule_lesson_time"),
        (
            "classcom",
            "0021_alter_plan_unique_together_remove_quarter_name_and_more",
        ),
    ]

    operations = []
