# Generated by Django 5.0.7 on 2024-08-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0021_resourcetypes_resourcetype_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="subtype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("BYLIST", "By list"),
                    ("BYCLASS", "By class"),
                    ("BYCLASSANDUNIT", "By class and unit"),
                    ("BYDEPARTMENT", "By Department"),
                    ("BYDOCS", "By docs"),
                    ("BYSCHOOL", "By school"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="resourcetypes",
            name="type",
            field=models.CharField(
                choices=[
                    ("BYLIST", "By list"),
                    ("BYCLASS", "By class"),
                    ("BYCLASSANDUNIT", "By class and unit"),
                    ("BYDEPARTMENT", "By Department"),
                    ("BYDOCS", "By docs"),
                    ("BYSCHOOL", "By school"),
                ]
            ),
        ),
    ]
