# Generated by Django 5.0.8 on 2024-10-12 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0021_alter_changemoderator_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="changemoderator",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "Moderatorni arizasi",
                "verbose_name_plural": "Moderator arizalari",
            },
        ),
    ]
