# Generated by Django 5.0.6 on 2024-06-19 05:43

import core.apps.classcom.models.schedule
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0022_merge_20240619_1042"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_time",
            field=models.CharField(
                default=1,
                max_length=25,
                validators=[
                    core.apps.classcom.models.schedule.validate_lesson_time
                ],
            ),
            preserve_default=False,
        ),
    ]
