# Generated by Django 5.1 on 2024-08-17 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0023_resource_created_at_resource_degree_resource_source_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="download",
            name="resource",
        ),
        migrations.AddField(
            model_name="download",
            name="media",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.media",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="download",
            name="moderator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.moderator",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="media",
            name="count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="media",
            name="download_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="downloaded_media",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="statistics",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
