# Generated by Django 5.0.8 on 2024-10-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0023_planappeal"),
    ]

    operations = [
        migrations.CreateModel(
            name="TmrFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Nomi",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Tasnifi"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/%Y/%m/%d/", verbose_name="Fayl"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Holati"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Turi",
                    ),
                ),
                (
                    "size",
                    models.BigIntegerField(
                        blank=True, default=0, null=True, verbose_name="Hajmi"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tmr Fayllari",
                "verbose_name_plural": "Tmr Fayllari",
            },
        ),
        migrations.AddField(
            model_name="planappeal",
            name="tmr_files",
            field=models.FileField(
                default=1,
                upload_to="tmr_appeals/",
                verbose_name="TMR fayllari",
            ),
            preserve_default=False,
        ),
    ]
