# Generated by Django 5.0.6 on 2024-06-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0024_alter_schedule_quarter"),
    ]

    operations = [
        migrations.AddField(
            model_name="daysoff",
            name="_class",
            field=models.ManyToManyField(to="classcom.classes"),
        ),
        migrations.AddField(
            model_name="daysoff",
            name="science",
            field=models.ManyToManyField(to="classcom.science"),
        ),
    ]
