# Generated by Django 5.0.8 on 2024-10-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0024_tmrfiles_planappeal_tmr_files"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="planappeal",
            name="tmr_files",
        ),
        migrations.AddField(
            model_name="planappeal",
            name="tmr_files",
            field=models.ManyToManyField(
                blank=True, to="classcom.tmrfiles", verbose_name="Fayllar"
            ),
        ),
    ]
