# Generated by Django 5.1 on 2024-08-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0024_remove_download_resource_download_media_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="download",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.moderator",
            ),
        ),
    ]
