# Generated by Django 5.0.6 on 2024-06-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0025_chat"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="response",
            field=models.TextField(blank=True, null=True),
        ),
    ]
