# Generated by Django 5.0.6 on 2024-06-20 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0025_rename_weekday_schedule_day"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="day",
            new_name="weekday",
        ),
    ]
