# Generated by Django 5.0.6 on 2024-06-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0025_daysoff__class_daysoff_science"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="sequence_number",
            field=models.IntegerField(default=1, unique=True),
        ),
    ]
