# Generated by Django 5.0.8 on 2024-10-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0025_remove_planappeal_tmr_files_planappeal_tmr_files"),
        ("http", "0008_user_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changemoderator",
            name="class_groups",
        ),
        migrations.RemoveField(
            model_name="changemoderator",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="changemoderator",
            name="science",
        ),
        migrations.RemoveField(
            model_name="planappeal",
            name="class_groups",
        ),
        migrations.RemoveField(
            model_name="planappeal",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="planappeal",
            name="science",
        ),
        migrations.AddField(
            model_name="changemoderator",
            name="class_groups",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.classgroup",
                verbose_name="Sinflar turlari",
            ),
        ),
        migrations.AddField(
            model_name="changemoderator",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AddField(
            model_name="changemoderator",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AddField(
            model_name="planappeal",
            name="class_groups",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.classgroup",
                verbose_name="Sinflar turlari",
            ),
        ),
        migrations.AddField(
            model_name="planappeal",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AddField(
            model_name="planappeal",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
    ]
