# Generated by Django 5.1 on 2024-08-17 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("classcom", "0025_alter_download_moderator"),
    ]

    operations = [
        migrations.AlterField(
            model_name="download",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.teacher",
            ),
        ),
    ]
