# Generated by Django 5.0.6 on 2024-06-24 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0026_topic_sequence_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
            ),
            preserve_default=False,
        ),
    ]
