# Generated by Django 5.1 on 2024-08-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0026_alter_download_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="file_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
