# Generated by Django 5.0.8 on 2024-10-14 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0026_remove_changemoderator_class_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changemoderator",
            name="science_type",
        ),
        migrations.RemoveField(
            model_name="planappeal",
            name="science_type",
        ),
        migrations.AddField(
            model_name="changemoderator",
            name="science_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.sciencetypes",
                verbose_name="Fan turi",
            ),
        ),
        migrations.AddField(
            model_name="planappeal",
            name="science_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.sciencetypes",
                verbose_name="Fan turi",
            ),
        ),
    ]
