# Generated by Django 5.0.6 on 2024-06-24 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0026_chat_response"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="response_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
