# Generated by Django 5.0.6 on 2024-06-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0026_chat_response"),
        ("classcom", "0026_rename_day_schedule_weekday"),
    ]

    operations = []
