# Generated by Django 5.0.6 on 2024-06-26 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0027_chat_response_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="topic",
        ),
        migrations.AddField(
            model_name="topic",
            name="thematic_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.plan",
            ),
        ),
    ]
