# Generated by Django 5.0.8 on 2024-10-14 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0027_remove_changemoderator_science_type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="planappeal",
            old_name="tmr_files",
            new_name="docs",
        ),
    ]
