# Generated by Django 5.0.6 on 2024-06-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0027_chat_response_time"),
        ("classcom", "0027_merge_20240624_1258"),
    ]

    operations = []
