# Generated by Django 5.0.6 on 2024-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0027_topic__class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="sequence_number",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("sequence_number", "science", "_class")},
        ),
    ]
