# Generated by Django 5.0.6 on 2024-06-25 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0028_alter_topic_sequence_number_and_more"),
        ("classcom", "0028_merge_20240624_1358"),
    ]

    operations = []
