# Generated by Django 5.1 on 2024-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "classcom",
            "0028_classtype_schedule_date_alter_schedule_weekday_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
    ]
