# Generated by Django 5.0.8 on 2024-10-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0028_rename_tmr_files_planappeal_docs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="changemoderator",
            name="science_type",
        ),
        migrations.AddField(
            model_name="changemoderator",
            name="science_type",
            field=models.ManyToManyField(
                blank=True, to="classcom.sciencetypes", verbose_name="Fan turi"
            ),
        ),
    ]
