# Generated by Django 5.0.6 on 2024-06-26 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0028_remove_plan_topic_topic_thematic_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="classcom.topic",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="thematic_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="classcom.plan",
            ),
        ),
    ]
