# Generated by Django 5.0.6 on 2024-06-26 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0029_plan_topic_alter_topic_thematic_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="_class",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="sequence_number",
            field=models.IntegerField(default=1),
        ),
    ]
