# Generated by Django 5.0.8 on 2024-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0029_remove_changemoderator_science_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="degree",
            field=models.CharField(
                choices=[
                    ("HIGHER", "Oliy toifa"),
                    ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                    (
                        "GOOD_TEACHER",
                        "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                    ),
                    ("AUTHOR", "Darslik muallifi"),
                    ("POPULAR", "Ommlashtirilgan"),
                ],
                default="AUTHOR",
                max_length=15,
                verbose_name="Daraja",
            ),
        ),
    ]
