# Generated by Django 5.1 on 2024-08-19 06:49

import core.apps.classcom.models.schedule
import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0029_alter_answer_created_at_alter_answer_updated_at_and_more",
        ),
        ("http", "0017_alter_schooltype_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="answer",
            options={
                "verbose_name": "Javob",
                "verbose_name_plural": "Javoblar",
            },
        ),
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "Kategoriya",
                "verbose_name_plural": "Kategoriyalar",
            },
        ),
        migrations.AlterModelOptions(
            name="categorytype",
            options={
                "verbose_name": "Kategoriya turi",
                "verbose_name_plural": "Kategoriyalar turi",
            },
        ),
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "Chat", "verbose_name_plural": "Chatlar"},
        ),
        migrations.AlterModelOptions(
            name="classes",
            options={"verbose_name": "Sinf", "verbose_name_plural": "Sinflar"},
        ),
        migrations.AlterModelOptions(
            name="classtype",
            options={
                "verbose_name": "Sinf turi",
                "verbose_name_plural": "Sinf turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="daysoff",
            options={
                "verbose_name": "Dam olish kuni",
                "verbose_name_plural": "Dam olish kunlari",
            },
        ),
        migrations.AlterModelOptions(
            name="download",
            options={
                "verbose_name": "Yuklamalar",
                "verbose_name_plural": "Yuklamalar",
            },
        ),
        migrations.AlterModelOptions(
            name="downloadtoken",
            options={
                "verbose_name": "Yuklash uchun token",
                "verbose_name_plural": "Yuklash uchun tokenlar",
            },
        ),
        migrations.AlterModelOptions(
            name="feedback",
            options={
                "verbose_name": "Fikr-mulohaza",
                "verbose_name_plural": "Fikr-mulohazalar",
            },
        ),
        migrations.AlterModelOptions(
            name="media",
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Medialar",
            },
        ),
        migrations.AlterModelOptions(
            name="moderator",
            options={
                "verbose_name": "Moderator",
                "verbose_name_plural": "Moderatorlar",
            },
        ),
        migrations.AlterModelOptions(
            name="notification",
            options={
                "verbose_name": "Bildirishnoma",
                "verbose_name_plural": "Bildirishnomalar",
            },
        ),
        migrations.AlterModelOptions(
            name="plan",
            options={
                "verbose_name": "Tematik reja",
                "verbose_name_plural": "Tematik rejalar",
            },
        ),
        migrations.AlterModelOptions(
            name="quarter",
            options={
                "verbose_name": "Chorak",
                "verbose_name_plural": "Choraklar",
            },
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "verbose_name": "Resurs",
                "verbose_name_plural": "Resurslar",
            },
        ),
        migrations.AlterModelOptions(
            name="resourcetype",
            options={
                "verbose_name": "Resurs turi",
                "verbose_name_plural": "Resurs turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "verbose_name": "Dars jadvali",
                "verbose_name_plural": "Dars jadvali",
            },
        ),
        migrations.AlterModelOptions(
            name="science",
            options={"verbose_name": "Fan", "verbose_name_plural": "Fanlar"},
        ),
        migrations.AlterModelOptions(
            name="sciencetypes",
            options={
                "verbose_name": "Fan turi",
                "verbose_name_plural": "Fan turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="settings",
            options={
                "verbose_name": "Sozlamalar",
                "verbose_name_plural": "Sozlamalar",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "verbose_name": "O'qituvchi",
                "verbose_name_plural": "O'qituvchilar",
            },
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="category",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="categorytype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="categorytype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="chat",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chat",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="classes",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classes",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="classtype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classtype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="daysoff",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="daysoff",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="download",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="download",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="moderator",
            name="plan_creatable",
            field=models.BooleanField(
                default=True, verbose_name="Tematik Reja yarata olishi"
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="quarter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quarter",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="resourcetypes",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resourcetypes",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="sciencetypes",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sciencetypes",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="settings",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="teacher",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="tempmoderator",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tempmoderator",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="body",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name="Javob",
            ),
        ),
        migrations.AlterField(
            model_name="answer",
            name="feedback",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="classcom.feedback",
                verbose_name="Fikr-mulohaza",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Kategoriya nomi"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kategoriya nomi"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kategoriya nomi"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kategoriya nomi"
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="name",
            field=models.CharField(
                max_length=255, verbose_name="Kategoriya turi"
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kategoriya turi"
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kategoriya turi"
            ),
        ),
        migrations.AlterField(
            model_name="categorytype",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Kategoriya turi"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="massage",
            field=models.TextField(verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="response",
            field=models.TextField(
                blank=True, null=True, verbose_name="Javob"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="response_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Javob vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="time",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Vaqt"),
        ),
        migrations.AlterField(
            model_name="chat",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Sinf nomi"),
        ),
        migrations.AlterField(
            model_name="classes",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf nomi"
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf nomi"
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf nomi"
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classtype",
                verbose_name="Sinf turi",
            ),
        ),
        migrations.AlterField(
            model_name="classtype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Sinf turi"),
        ),
        migrations.AlterField(
            model_name="classtype",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf turi"
            ),
        ),
        migrations.AlterField(
            model_name="classtype",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf turi"
            ),
        ),
        migrations.AlterField(
            model_name="classtype",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf turi"
            ),
        ),
        migrations.AlterField(
            model_name="daysoff",
            name="_class",
            field=models.ManyToManyField(
                to="classcom.classes", verbose_name="Sinflar"
            ),
        ),
        migrations.AlterField(
            model_name="daysoff",
            name="from_date",
            field=models.DateField(verbose_name="Boshlang'ich sana"),
        ),
        migrations.AlterField(
            model_name="daysoff",
            name="reason",
            field=models.CharField(max_length=255, verbose_name="Sababi"),
        ),
        migrations.AlterField(
            model_name="daysoff",
            name="science",
            field=models.ManyToManyField(
                to="classcom.science", verbose_name="Fanlar"
            ),
        ),
        migrations.AlterField(
            model_name="daysoff",
            name="to_date",
            field=models.DateField(verbose_name="Oxirgi sana"),
        ),
        migrations.AlterField(
            model_name="daysoff",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="days_off",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="date",
            field=models.DateField(verbose_name="Sanasi"),
        ),
        migrations.AlterField(
            model_name="download",
            name="media",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.media",
                verbose_name="Media",
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="moderator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.moderator",
                verbose_name="Moderator",
            ),
        ),
        migrations.AlterField(
            model_name="download",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.teacher",
                verbose_name="O'qituvchi",
            ),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="download",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.download",
                verbose_name="Yuklama",
            ),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="expires_at",
            field=models.DateTimeField(verbose_name="Muddati"),
        ),
        migrations.AlterField(
            model_name="downloadtoken",
            name="token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                unique=True,
                verbose_name="Token",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="answered",
            field=models.BooleanField(
                default=False, verbose_name="Javob berildimi"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="body",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(1000)],
                verbose_name="Mazmuni",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[("first", "First"), ("second", "Second")],
                max_length=10,
                verbose_name="Feedback turi",
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="count",
            field=models.IntegerField(
                default=0, verbose_name="Yuklashlar soni"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="desc",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="desc_en",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="desc_ru",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="desc_uz",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="download_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="downloaded_media",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Yuklab olganlar",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(upload_to="media/", verbose_name="Fayl"),
        ),
        migrations.AlterField(
            model_name="media",
            name="file_type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Fayl turi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="name_uz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="size",
            field=models.BigIntegerField(
                blank=True, default=0, null=True, verbose_name="Hajmi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="statistics",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Statistika",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Turi"
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="balance",
            field=models.BigIntegerField(default=0, verbose_name="Balans"),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="degree",
            field=models.CharField(
                choices=[
                    ("HIGHER", "Oliy toifa"),
                    ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                    (
                        "GOOD_TEACHER",
                        "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                    ),
                    ("AUTHOR", "Darslik muallifi"),
                ],
                default="AUTHOR",
                max_length=15,
                verbose_name="Daraja",
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="docs",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                verbose_name="Hujjat",
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="is_contracted",
            field=models.BooleanField(default=False, verbose_name="Shartnoma"),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="science",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="science_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.sciencetypes",
                verbose_name="Fan turi",
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="O'qilgan"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message",
            field=models.TextField(verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message_en",
            field=models.TextField(null=True, verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message_ru",
            field=models.TextField(null=True, verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="message_uz",
            field=models.TextField(null=True, verbose_name="Xabar"),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="banner",
            field=models.ImageField(
                upload_to="plan/banner/", verbose_name="Banner"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="classes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="hour",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Soat"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_resource",
            field=models.ManyToManyField(
                blank=True, to="classcom.media", verbose_name="Resurslar"
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="quarter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.quarter",
                verbose_name="Chorak",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="science",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plans",
                to="classcom.topic",
                verbose_name="Mavzu",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.resourcetype",
                verbose_name="Resurs turi",
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="choices",
            field=models.IntegerField(
                choices=[
                    (1, "First Quarter"),
                    (2, "Second Quarter"),
                    (3, "Third Quarter"),
                    (4, "Fourth Quarter"),
                ],
                default=1,
                verbose_name="Chorak",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="end_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.today,
                verbose_name="Oxirgi sana",
            ),
        ),
        migrations.AlterField(
            model_name="quarter",
            name="start_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime.today,
                verbose_name="Boshlang'ich sana",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="banner",
            field=models.ImageField(
                upload_to="resource_banners/", verbose_name="Banner"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.category",
                verbose_name="Kategoriya",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="category_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.categorytype",
                verbose_name="Kategoriya turi",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="degree",
            field=models.CharField(
                choices=[
                    ("LOW", "Past"),
                    ("MEDIUM", "O'rta"),
                    ("HIGH", "Yuqori"),
                ],
                default="MEDIUM",
                verbose_name="Daraja",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="description_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="resources",
                to="classcom.media",
                verbose_name="Media",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="source",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Manba"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="subtype",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Resurs sub turi",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.resourcetype",
                verbose_name="Resurs turi",
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="resource",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="resourcetype",
            name="type",
            field=models.CharField(
                choices=[
                    ("BYLIST", "By list"),
                    ("BYCLASS", "By class"),
                    ("BYCLASSANDUNIT", "By class and unit"),
                    ("BYDEPARTMENT", "By Department"),
                    ("BYDOCS", "By docs"),
                    ("BYSCHOOL", "By school"),
                ],
                max_length=255,
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="resourcetypes",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="resourcetypes",
            name="type",
            field=models.CharField(
                choices=[
                    ("BYLIST", "By list"),
                    ("BYCLASS", "By class"),
                    ("BYCLASSANDUNIT", "By class and unit"),
                    ("BYDEPARTMENT", "By Department"),
                    ("BYDOCS", "By docs"),
                    ("BYSCHOOL", "By school"),
                ],
                max_length=255,
                verbose_name="Turi",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="classes",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="date",
            field=models.DateField(verbose_name="Sana"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="end_time",
            field=models.TimeField(verbose_name="Tugash vaqti"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="lesson_time",
            field=models.CharField(
                max_length=25,
                validators=[
                    core.apps.classcom.models.schedule.validate_lesson_time
                ],
                verbose_name="Dars vaqti",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="quarter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.quarter",
                verbose_name="Chorak",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="science",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="shift",
            field=models.CharField(
                choices=[("MORNING", "Ertalabki"), ("EVENING", "Kechki")],
                default="MORNING",
                max_length=255,
                verbose_name="Smena",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="start_time",
            field=models.TimeField(verbose_name="Boshlanish vaqti"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Dushanba"),
                    ("tuesday", "Seshanba"),
                    ("wednesday", "Chorshanba"),
                    ("thursday", "Payshanba"),
                    ("friday", "Juma"),
                    ("saturday", "Shanba"),
                ],
                max_length=15,
                null=True,
                verbose_name="Kun",
            ),
        ),
        migrations.AlterField(
            model_name="science",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="science",
            name="name",
            field=models.CharField(verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="science",
            name="name_en",
            field=models.CharField(null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="science",
            name="name_ru",
            field=models.CharField(null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="science",
            name="name_uz",
            field=models.CharField(null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="science",
            name="science_grp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="http.sciencegroups",
                verbose_name="Fan guruhi",
            ),
        ),
        migrations.AlterField(
            model_name="science",
            name="types",
            field=models.ManyToManyField(
                to="classcom.sciencetypes", verbose_name="Fan turi"
            ),
        ),
        migrations.AlterField(
            model_name="science",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default=django.utils.timezone.now,
                verbose_name="Yangilangan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name",
            field=models.CharField(verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name_en",
            field=models.CharField(null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name_ru",
            field=models.CharField(null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name_uz",
            field=models.CharField(null=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="settings",
            name="key",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Key"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="value",
            field=models.TextField(verbose_name="Qiymati"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="payment_status",
            field=models.BooleanField(
                default=False, verbose_name="To'lov holati"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="science",
            field=models.ManyToManyField(
                blank=True, to="classcom.science", verbose_name="Fanlar"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="balance",
            field=models.BigIntegerField(default=0, verbose_name="Balans"),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="degree",
            field=models.CharField(
                choices=[
                    ("HIGHER", "Oliy toifa"),
                    ("EXCELLENT", "Xalq ta'limi a'lochisi"),
                    (
                        "GOOD_TEACHER",
                        "\"Eng yaxshi o'qituvchi\" konkursi g'olibi",
                    ),
                    ("AUTHOR", "Darslik muallifi"),
                ],
                default="AUTHOR",
                max_length=15,
                verbose_name="Daraja",
            ),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="docs",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/",
                verbose_name="Hujjat",
            ),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="is_contracted",
            field=models.BooleanField(default=False, verbose_name="Shartnoma"),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="science",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="science_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.sciencetypes",
                verbose_name="Fan turi",
            ),
        ),
        migrations.AlterField(
            model_name="tempmoderator",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="quarter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.quarter",
                verbose_name="Chorak",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="science",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="sequence_number",
            field=models.IntegerField(default=1, verbose_name="Tartib raqami"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="thematic_plan",
            field=models.ManyToManyField(
                blank=True,
                related_name="topics",
                to="classcom.plan",
                verbose_name="Tematik reja",
            ),
        ),
        migrations.AlterModelTable(
            name="answer",
            table="answer",
        ),
    ]
