# Generated by Django 5.1 on 2024-08-18 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0029_alter_classes_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
