# Generated by Django 5.1 on 2024-08-18 10:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0030_schedule_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="weekday",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monday", "Monday"),
                    ("tuesday", "Tuesday"),
                    ("wednesday", "Wednesday"),
                    ("thursday", "Thursday"),
                    ("friday", "Friday"),
                    ("saturday", "Saturday"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="schedule",
            unique_together={("date", "start_time", "end_time", "user")},
        ),
    ]
