# Generated by Django 5.0.6 on 2024-06-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0026_topic_sequence_number"),
        ("classcom", "0028_merge_20240624_1358"),
        ("classcom", "0030_topic__class_topic_sequence_number"),
    ]

    operations = []
