# Generated by Django 5.1 on 2024-08-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0030_alter_answer_options_alter_category_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="resource_creatable",
            field=models.BooleanField(
                default=True, verbose_name="Resurs yarata olishi."
            ),
        ),
    ]
