# Generated by Django 5.1 on 2024-08-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0031_moderator_resource_creatable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sciencetypes",
            name="name",
            field=models.CharField(verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name_en",
            field=models.CharField(null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name_ru",
            field=models.CharField(null=True, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="sciencetypes",
            name="name_uz",
            field=models.CharField(null=True, verbose_name="Nomi"),
        ),
    ]
