# Generated by Django 5.1.2 on 2024-11-06 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0031_remove_planappeal_class_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="is_read",
            field=models.BooleanField(default=False, verbose_name="O'qildi"),
        ),
    ]
