# Generated by Django 5.1 on 2024-08-19 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0032_alter_sciencetypes_name_alter_sciencetypes_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="class_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.classtype",
                verbose_name="Sinflar turi",
            ),
            preserve_default=False,
        ),
    ]
