# Generated by Django 5.0.8 on 2024-12-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0032_chat_is_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="response_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="documents/%Y/%m/%d/",
                verbose_name="Javob fayli",
            ),
        ),
    ]
