# Generated by Django 5.1 on 2024-08-20 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0033_schedule_class_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="science",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tartib raqami"
            ),
        ),
    ]
