# Generated by Django 5.1 on 2024-08-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0034_science_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tartib raqami"
            ),
        ),
    ]
