# Generated by Django 5.0.8 on 2024-08-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0036_alter_schedule_unique_together_schedule_name_weeks_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="resource",
            field=models.ManyToManyField(
                related_name="moderators",
                to="classcom.resource",
                verbose_name="Resurslar",
            ),
        ),
    ]
