# Generated by Django 5.0.8 on 2024-08-21 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0037_moderator_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moderator",
            name="resource",
        ),
        migrations.AddField(
            model_name="moderator",
            name="resource_type",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderators",
                to="classcom.resourcetype",
                verbose_name="Resurs turlari",
            ),
        ),
    ]
