# Generated by Django 5.0.8 on 2024-08-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0038_remove_moderator_resource_moderator_resource_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderator",
            name="plan_creatable",
            field=models.BooleanField(
                default=False, verbose_name="Tematik Reja yarata olishi"
            ),
        ),
        migrations.AlterField(
            model_name="moderator",
            name="resource_creatable",
            field=models.BooleanField(
                default=False, verbose_name="Resurs yarata olishi."
            ),
        ),
    ]
