# Generated by Django 5.0.8 on 2024-08-22 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0039_alter_moderator_plan_creatable_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="schedulechoices",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="name",
        ),
        migrations.CreateModel(
            name="ScheduleTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Dars jadval shablon nomi",
                    ),
                ),
                (
                    "schedules",
                    models.ManyToManyField(
                        related_name="schedule_templates",
                        to="classcom.schedule",
                        verbose_name="Dars jadvalar",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="schedulechoices",
            name="schedule_template",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.scheduletemplate",
                verbose_name="Dars jadval shabloni",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="schedulechoices",
            name="schedule",
        ),
    ]
