# Generated by Django 5.0.8 on 2024-08-22 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0041_alter_schedule_unique_together_scheduletemplate_user",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "ordering": ["weekday", "lesson_time"],
                "verbose_name": "Dars jadvali",
                "verbose_name_plural": "Dars jadvali",
            },
        ),
    ]
