# Generated by Django 5.0.8 on 2024-08-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0045_science_class_group"),
        ("http", "0026_remove_classgroup_school_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="science",
            name="class_group",
        ),
        migrations.AddField(
            model_name="science",
            name="class_group",
            field=models.ManyToManyField(
                to="http.classgroup", verbose_name="Sinf turi"
            ),
        ),
    ]
