# Generated by Django 5.0.8 on 2024-08-23 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0047_remove_science_class_group_science_class_group"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="science",
            options={
                "ordering": ["order_number"],
                "verbose_name": "Fan",
                "verbose_name_plural": "Fanlar",
            },
        ),
    ]
