# Generated by Django 5.0.8 on 2024-08-23 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0048_alter_science_options"),
        ("http", "0026_remove_classgroup_school_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="science",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.classgroup",
                verbose_name="Sinf turi",
            ),
        ),
        migrations.AlterField(
            model_name="science",
            name="science_grp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.sciencegroups",
                verbose_name="Fan guruhi",
            ),
        ),
    ]
