# Generated by Django 5.0.8 on 2024-08-24 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0049_alter_science_class_group_alter_science_science_grp",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="thematic_plan",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="topic",
        ),
        migrations.AddField(
            model_name="plan",
            name="topic",
            field=models.ManyToManyField(
                related_name="plans", to="classcom.topic", verbose_name="Mavzu"
            ),
        ),
    ]
