# Generated by Django 5.0.8 on 2024-08-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0050_remove_topic_thematic_plan_remove_plan_topic_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="topic",
        ),
    ]
