# Generated by Django 5.0.8 on 2024-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0051_remove_plan_topic"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ResourceTypes",
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": ["order_number"],
                "verbose_name": "Resurs",
                "verbose_name_plural": "Resurslar",
            },
        ),
        migrations.RemoveField(
            model_name="plan",
            name="plan_resource",
        ),
        migrations.AddField(
            model_name="plan",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Faol"),
        ),
        migrations.AddField(
            model_name="plan",
            name="topic",
            field=models.ManyToManyField(
                blank=True,
                related_name="plans",
                to="classcom.topic",
                verbose_name="Mavzu",
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="media",
            field=models.ManyToManyField(
                related_name="topic", to="classcom.media", verbose_name="Media"
            ),
        ),
    ]
