# Generated by Django 5.0.8 on 2024-08-24 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0052_delete_resourcetypes_alter_resource_options_and_more",
        ),
        ("http", "0026_remove_classgroup_school_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="class_group",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="http.classgroup",
                verbose_name="Sinflar guruhi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plan",
            name="science_types",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.sciencetypes",
                verbose_name="Fan guruhi",
            ),
            preserve_default=False,
        ),
    ]
