# Generated by Django 5.0.8 on 2024-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0053_plan_class_group_plan_science_types"),
    ]

    operations = [
        migrations.CreateModel(
            name="LanguageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("UZ", "O'zbek tili"), ("RU", "Rus tili")],
                        max_length=2,
                    ),
                ),
            ],
        ),
    ]
