# Generated by Django 5.0.8 on 2024-08-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0054_languagemodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="languages",
            field=models.ManyToManyField(
                related_name="models", to="classcom.languagemodel"
            ),
        ),
    ]
