# Generated by Django 5.0.8 on 2024-08-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0055_plan_languages"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="languages",
        ),
        migrations.AddField(
            model_name="plan",
            name="language",
            field=models.CharField(
                choices=[("UZ", "O'zbek tili"), ("RU", "Rus tili")],
                default="UZ",
                max_length=2,
            ),
        ),
    ]
