# Generated by Django 5.0.8 on 2024-08-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0056_remove_plan_languages_plan_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagemodel",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                default="uz",
                max_length=2,
            ),
        ),
    ]
