# Generated by Django 5.0.8 on 2024-08-24 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0057_alter_languagemodel_language_alter_plan_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="description",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="description_en",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="description_ru",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="description_uz",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="name",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="name_uz",
        ),
    ]
