# Generated by Django 5.0.8 on 2024-08-24 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0058_remove_plan_banner_remove_plan_description_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="_class",
            new_name="classes",
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together={("sequence_number", "science", "classes")},
        ),
    ]
