# Generated by Django 5.0.8 on 2024-08-24 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0059_rename__class_topic_classes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                default="uz",
                max_length=2,
                verbose_name="Til",
            ),
        ),
    ]
