# Generated by Django 5.0.8 on 2024-08-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0060_alter_plan_language"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topic",
            options={
                "ordering": ["sequence_number"],
                "verbose_name": "Mavzu",
                "verbose_name_plural": "Mavzular",
            },
        ),
        migrations.AlterUniqueTogether(
            name="topic",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="topic",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tavsif"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="hours",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Soatlar"
            ),
        ),
        migrations.RemoveField(
            model_name="topic",
            name="classes",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="quarter",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="science",
        ),
    ]
