# Generated by Django 5.0.8 on 2024-08-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0061_alter_topic_options_alter_topic_unique_together_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="media",
            name="file_type",
        ),
        migrations.RemoveField(
            model_name="media",
            name="name_en",
        ),
        migrations.RemoveField(
            model_name="media",
            name="name_ru",
        ),
        migrations.RemoveField(
            model_name="media",
            name="name_uz",
        ),
        migrations.AlterField(
            model_name="media",
            name="type",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Fayl turi"
            ),
        ),
    ]
