# Generated by Django 5.0.8 on 2024-08-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0062_remove_media_file_type_remove_media_name_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="topic/banner/",
                verbose_name="Banner",
            ),
        ),
    ]
