# Generated by Django 5.0.8 on 2024-08-26 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0063_topic_banner"),
        ("http", "0026_remove_classgroup_school_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="class_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderators",
                to="http.classgroup",
                verbose_name="Sinflar turlari",
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderators",
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderators",
                to="classcom.languagemodel",
                verbose_name="Tillar",
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="quarters",
            field=models.ManyToManyField(
                blank=True,
                related_name="moderators",
                to="classcom.quarter",
                verbose_name="Choraklar",
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="topic_creatable",
            field=models.BooleanField(
                default=False, verbose_name="Mavzu yarata olishi."
            ),
        ),
        migrations.RemoveField(
            model_name="moderator",
            name="science",
        ),
        migrations.RemoveField(
            model_name="moderator",
            name="science_type",
        ),
        migrations.AddField(
            model_name="moderator",
            name="science",
            field=models.ManyToManyField(
                blank=True, to="classcom.science", verbose_name="Fan"
            ),
        ),
        migrations.AddField(
            model_name="moderator",
            name="science_type",
            field=models.ManyToManyField(
                blank=True, to="classcom.sciencetypes", verbose_name="Fan turi"
            ),
        ),
    ]
