# Generated by Django 5.0.8 on 2024-08-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0064_moderator_class_groups_moderator_classes_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="classes",
            options={
                "ordering": ("order_number",),
                "verbose_name": "Sinf",
                "verbose_name_plural": "Sinflar",
            },
        ),
        migrations.AlterModelOptions(
            name="languagemodel",
            options={"verbose_name": "Til", "verbose_name_plural": "Tillar"},
        ),
        migrations.AddField(
            model_name="classes",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tartib raqami"
            ),
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="language",
            field=models.CharField(
                choices=[("uz", "O'zbek tili"), ("ru", "Rus tili")],
                max_length=2,
                verbose_name="Til",
            ),
        ),
    ]
