# Generated by Django 5.0.8 on 2024-08-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0065_alter_classes_options_alter_languagemodel_options_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moderator",
            name="topic_creatable",
        ),
    ]
