# Generated by Django 5.0.8 on 2024-08-26 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0066_remove_moderator_topic_creatable"),
        ("http", "0026_remove_classgroup_school_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="http.classgroup",
                verbose_name="Sinflar guruhi",
            ),
        ),
    ]
