# Generated by Django 5.0.8 on 2024-08-27 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0067_schedule_class_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="media_creatable",
            field=models.BooleanField(
                default=False, verbose_name="Media yarata olishi."
            ),
        ),
    ]
