# Generated by Django 5.0.8 on 2024-08-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0068_topic_media_creatable"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagemodel",
            name="name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Nomi"
            ),
            preserve_default=False,
        ),
    ]
