# Generated by Django 5.0.8 on 2024-08-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0069_languagemodel_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagemodel",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AddField(
            model_name="languagemodel",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AddField(
            model_name="languagemodel",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
    ]
