# Generated by Django 5.0.8 on 2024-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0070_languagemodel_name_en_languagemodel_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="type",
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="name_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="name_ru",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
        migrations.AlterField(
            model_name="languagemodel",
            name="name_uz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nomi"
            ),
        ),
    ]
