# Generated by Django 5.0.8 on 2024-08-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0071_remove_plan_type_alter_languagemodel_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="moderator",
            name="topic_creatable",
            field=models.BooleanField(
                default=False, verbose_name="Mavzu yarata olishi."
            ),
        ),
    ]
