# Generated by Django 5.0.8 on 2024-08-27 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0072_moderator_topic_creatable"),
        ("http", "0026_remove_classgroup_school_type_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together={
                (
                    "classes",
                    "quarter",
                    "science",
                    "class_group",
                    "science_types",
                )
            },
        ),
    ]
