# Generated by Django 5.0.8 on 2024-08-27 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0073_alter_plan_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="banner",
        ),
    ]
