# Generated by Django 5.0.8 on 2024-08-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0074_remove_topic_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="media",
            field=models.ManyToManyField(
                blank=True,
                related_name="topic",
                to="classcom.media",
                verbose_name="Media",
            ),
        ),
    ]
