# Generated by Django 5.0.8 on 2024-08-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0076_media_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="weeks",
            field=models.PositiveIntegerField(
                blank=True, default=1, null=True, verbose_name="Haftalar"
            ),
        ),
    ]
