# Generated by Django 5.0.8 on 2024-08-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0077_topic_weeks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduletemplate",
            options={
                "ordering": ["name"],
                "verbose_name": "Dars jadval shabloni",
                "verbose_name_plural": "Dars jadval shabloni",
            },
        ),
        migrations.AddField(
            model_name="resourcetype",
            name="order_number",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Tartib raqami"
            ),
        ),
    ]
