# Generated by Django 5.0.8 on 2024-08-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0079_alter_resourcetype_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="moderator",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Moderator",
                "verbose_name_plural": "Moderatorlar",
            },
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "O'qituvchi",
                "verbose_name_plural": "O'qituvchilar",
            },
        ),
    ]
