# Generated by Django 5.0.8 on 2024-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0080_alter_moderator_options_alter_teacher_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourcetype",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Aktiv"),
        ),
    ]
