# Generated by Django 5.0.8 on 2024-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("websocket", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_sending",
            field=models.BooleanField(
                default=False, verbose_name="Jo'natilmoqda"
            ),
        ),
    ]
