# Generated by Django 5.0.8 on 2024-09-24 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0006_alter_ai_options"),
        ("http", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="default_document",
            field=models.FileField(
                blank=True,
                default="assets/document.pdf",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="document",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.document",
                verbose_name="Hujjat",
            ),
        ),
    ]
