# Generated by Django 5.0.8 on 2024-09-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0002_user_default_document_user_document"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="default_document",
        ),
        migrations.AddField(
            model_name="user",
            name="default_document_ru",
            field=models.FileField(
                blank=True,
                default="assets/document_ru.docx",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="default_document_uz",
            field=models.FileField(
                blank=True,
                default="assets/document_uz.docx",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat",
            ),
        ),
    ]
