# Generated by Django 5.0.8 on 2024-09-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0006_alter_ai_options"),
        ("http", "0003_remove_user_default_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="document",
        ),
        migrations.AddField(
            model_name="user",
            name="document",
            field=models.ManyToManyField(
                blank=True, to="classcom.document", verbose_name="Hujjat"
            ),
        ),
    ]
