# Generated by Django 5.0.8 on 2024-09-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0004_remove_user_document_user_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_document_ru",
            field=models.FileField(
                blank=True,
                default="media/doc/document_ru.pdf",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat (rus)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_document_uz",
            field=models.FileField(
                blank=True,
                default="media/doc/document_uz.pdf",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat (uz)",
            ),
        ),
    ]
