# Generated by Django 5.0.8 on 2024-09-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0005_alter_user_default_document_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="response_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="response_file/",
                verbose_name="Javob hujjati",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="status_file",
            field=models.CharField(
                choices=[
                    ("NO_FILE", "Hujjat yuklanmagan"),
                    ("WAITING", "Hujjat topshirgan"),
                    ("ACCEPTED", "Hujjat qabul qilindi"),
                ],
                default="NO_FILE",
                max_length=255,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_document_ru",
            field=models.FileField(
                blank=True,
                default="doc/document_ru.pdf",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat (rus)",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="default_document_uz",
            field=models.FileField(
                blank=True,
                default="doc/document_uz.pdf",
                null=True,
                upload_to="documents/",
                verbose_name="Standart hujjat (uz)",
            ),
        ),
    ]
