# Generated by Django 5.0.4 on 2024-04-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('http', '0005_user_institution_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
