# Generated by Django 5.0.8 on 2024-09-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0006_user_response_file_user_status_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status_file",
            field=models.CharField(
                choices=[
                    ("NO_FILE", "Hujjat yuklanmagan"),
                    ("WAITING", "Hujjat topshirgan"),
                    ("ACCEPTED", "Shartnoma tuzilgan"),
                ],
                default="NO_FILE",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
