# Generated by Django 5.0.6 on 2024-05-30 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0007_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatar/"
            ),
        ),
    ]
