# Generated by Django 5.0.6 on 2024-06-04 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http", "0008_user_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="http.region",
            ),
        ),
    ]
