# Generated by Django 5.0.8 on 2024-10-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0008_user_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="father_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Otasining ismi",
            ),
        ),
    ]
