# Generated by Django 5.0.8 on 2024-12-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0010_remove_user_science_group_user_science_group"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="status_file",
            field=models.CharField(
                choices=[
                    ("NO_FILE", "Hujjat yuklanmagan"),
                    ("WAITING", "Hujjat topshirgan"),
                    ("ACCEPTED", "Shartnoma tuzilgan"),
                    ("REJECTED", "Shartnoma bekor qilingan"),
                ],
                default="NO_FILE",
                max_length=255,
                verbose_name="Status",
            ),
        ),
    ]
