# Generated by Django 5.0.7 on 2024-07-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http", "0011_alter_user_district_alter_user_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="district_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="district_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="district_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="region_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="region_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="region",
            name="region_uz",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sciencegroups",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sciencegroups",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="sciencegroups",
            name="name_uz",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
