# Generated by Django 5.0.7 on 2024-07-22 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "classcom",
            "0006_classes_name_en_classes_name_ru_classes_name_uz_and_more",
        ),
        ("http", "0012_district_district_en_district_district_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.classes",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.science",
            ),
        ),
    ]
