# Generated by Django 5.0.7 on 2024-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http", "0013_user_classes_user_science"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsconfirm",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
