# Generated by Django 5.1 on 2024-08-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http", "0014_alter_smsconfirm_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "SchoolType",
                "verbose_name_plural": "SchoolTypes",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="school_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.schooltype",
            ),
        ),
    ]
