# Generated by Django 5.1 on 2024-08-19 05:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http", "0015_schooltype_user_school_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="schooltype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schooltype",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
