# Generated by Django 5.1 on 2024-08-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("http", "0016_schooltype_created_at_schooltype_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schooltype",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="schooltype",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
    ]
