# Generated by Django 5.1 on 2024-08-19 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0030_alter_answer_options_alter_category_options_and_more",
        ),
        ("http", "0017_alter_schooltype_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schooltype",
            options={
                "verbose_name": "Maktab turi",
                "verbose_name_plural": "Maktab turlari",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Foydalanuvchilar",
                "verbose_name_plural": "Foydalanuvchilar",
            },
        ),
        migrations.AddField(
            model_name="basecomment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="basecomment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="comment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="comment",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="district",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="frontendtranslation",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="frontendtranslation",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="region",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="sciencegroups",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sciencegroups",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="smsconfirm",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="smsconfirm",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="tags",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tags",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="basecomment",
            name="comments",
            field=models.ManyToManyField(
                blank=True, to="http.comment", verbose_name="Izohlar"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.CharField(max_length=255, verbose_name="Matn"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district",
            field=models.CharField(max_length=255, verbose_name="Tuman"),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="district_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Tuman"
            ),
        ),
        migrations.AlterField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="http.region",
                verbose_name="Viloyat",
            ),
        ),
        migrations.AlterField(
            model_name="frontendtranslation",
            name="key",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Key"
            ),
        ),
        migrations.AlterField(
            model_name="frontendtranslation",
            name="value",
            field=models.TextField(verbose_name="Qiymati"),
        ),
        migrations.AlterField(
            model_name="frontendtranslation",
            name="value_en",
            field=models.TextField(null=True, verbose_name="Qiymati"),
        ),
        migrations.AlterField(
            model_name="frontendtranslation",
            name="value_ru",
            field=models.TextField(null=True, verbose_name="Qiymati"),
        ),
        migrations.AlterField(
            model_name="frontendtranslation",
            name="value_uz",
            field=models.TextField(null=True, verbose_name="Qiymati"),
        ),
        migrations.AlterField(
            model_name="post",
            name="desc",
            field=models.TextField(verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="post",
            name="desc_en",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="post",
            name="desc_ru",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="post",
            name="desc_uz",
            field=models.TextField(null=True, verbose_name="Tavsif"),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="posts/", verbose_name="Rasm"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, to="http.tags", verbose_name="Teglar"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Sarlavha"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sarlavha"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region",
            field=models.CharField(max_length=255, verbose_name="Viloyat"),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="region_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Viloyat"
            ),
        ),
        migrations.AlterField(
            model_name="schooltype",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Maktab turi"),
        ),
        migrations.AlterField(
            model_name="sciencegroups",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Fan guruhi"),
        ),
        migrations.AlterField(
            model_name="sciencegroups",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Fan guruhi"
            ),
        ),
        migrations.AlterField(
            model_name="sciencegroups",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Fan guruhi"
            ),
        ),
        migrations.AlterField(
            model_name="sciencegroups",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Fan guruhi"
            ),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="code",
            field=models.IntegerField(verbose_name="Kod"),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="expire_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Muddati"
            ),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="phone",
            field=models.CharField(
                max_length=255, verbose_name="Telefon raqami"
            ),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="resend_count",
            field=models.IntegerField(
                default=0, verbose_name="Qayta yuborishlar soni"
            ),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="resend_unlock_time",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="Qayta yuborish bloklanish vaqti",
            ),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="try_count",
            field=models.IntegerField(
                default=0, verbose_name="Urinishlar soni"
            ),
        ),
        migrations.AlterField(
            model_name="smsconfirm",
            name="unlock_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Bloklanish vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="tags",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nomi"),
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatar/",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="classes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.classes",
                verbose_name="Sinflar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.district",
                verbose_name="Tuman",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OLIY", "Oliy"),
                    ("O'rta maxsus", "O'rta maxsus"),
                    ("O'rta", "O'rta"),
                ],
                max_length=255,
                null=True,
                verbose_name="Muassasa",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution_number",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Muassasa raqami",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Telefon"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.region",
                verbose_name="Viloyat",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("user", "Foydalanuvchi"),
                ],
                default="user",
                max_length=255,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="school_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.schooltype",
                verbose_name="Maktab turi",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="science",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="science_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.sciencegroups",
                verbose_name="Fan guruhi",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Foydalanuvchi nomi",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="validated_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Tasdiqlangan vaqti"
            ),
        ),
    ]
