# Generated by Django 5.1 on 2024-08-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0018_alter_schooltype_options_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="district",
            options={
                "verbose_name": "Tuman",
                "verbose_name_plural": "Tumanlar",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={
                "verbose_name": "Viloyat",
                "verbose_name_plural": "Viloyatlar",
            },
        ),
        migrations.AlterModelOptions(
            name="sciencegroups",
            options={
                "verbose_name": "Fan guruhi",
                "verbose_name_plural": "Fan guruhi",
            },
        ),
    ]
