# Generated by Django 5.1 on 2024-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0019_alter_district_options_alter_region_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("user", "Foydalanuvchi"),
                ],
                default="user",
                max_length=255,
                null=True,
                verbose_name="Rol",
            ),
        ),
    ]
