# Generated by Django 5.1 on 2024-08-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0020_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="schooltype",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Maktab turi"
            ),
        ),
        migrations.AddField(
            model_name="schooltype",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Maktab turi"
            ),
        ),
        migrations.AddField(
            model_name="schooltype",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Maktab turi"
            ),
        ),
    ]
