# Generated by Django 5.1 on 2024-08-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0021_schooltype_name_en_schooltype_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schooltype",
            name="institution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("OLIY", "Oliy"),
                    ("O'rta maxsus", "O'rta maxsus"),
                    ("O'rta", "O'rta"),
                ],
                max_length=255,
                null=True,
                verbose_name="Muassasa",
            ),
        ),
    ]
