# Generated by Django 5.0.8 on 2024-08-22 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classcom", "0044_delete_notification"),
        ("http", "0022_schooltype_institution"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Sinf turi"),
                ),
                (
                    "school_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="http.schooltype",
                        verbose_name="Maktab turi",
                    ),
                ),
                (
                    "science",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_groups",
                        to="classcom.science",
                        verbose_name="Fan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sinf turi",
                "verbose_name_plural": "Sinf turlari",
            },
        ),
    ]
