# Generated by Django 5.0.8 on 2024-08-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0023_classgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="classgroup",
            name="name_en",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf turi"
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="name_ru",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf turi"
            ),
        ),
        migrations.AddField(
            model_name="classgroup",
            name="name_uz",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Sinf turi"
            ),
        ),
    ]
