# Generated by Django 5.0.8 on 2024-08-22 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0024_classgroup_name_en_classgroup_name_ru_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="class_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="http.classgroup",
                verbose_name="Sinf turi",
            ),
        ),
    ]
