# Generated by Django 5.0.8 on 2024-08-23 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0025_user_class_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classgroup",
            name="school_type",
        ),
        migrations.RemoveField(
            model_name="classgroup",
            name="science",
        ),
    ]
