from .category import *  # noqa
from .chat import *  # noqa
from .classes import *  # noqa
from .daysoff import *  # noqa
from .download import *  # noqa
from .feedback import *  # noqa
from .media import *  # noqa
from .moderator import *  # noqa
from .plan import *  # noqa
from .quarter import *  # noqa
from .recource import *  # noqa
from .resource_type import *  # noqa
from .schedule import *  # noqa
from .science import *  # noqa
from .settings import *  # noqa
from .teacher import *  # noqa
from .topic import *  # noqa
from .weeks import *  # noqa
