# Generated by Django 5.0.8 on 2024-08-30 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("classcom", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Boshlanish sanasi",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Tugash sanasi"
                    ),
                ),
                (
                    "price",
                    models.BigIntegerField(default=0, verbose_name="Narxi"),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Holati"),
                ),
                (
                    "science",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classcom.science",
                        verbose_name="Fan",
                    ),
                ),
                (
                    "types",
                    models.ManyToManyField(
                        to="classcom.sciencetypes", verbose_name="Fan turi"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Buyurtmalar",
                "verbose_name_plural": "Buyurtmalar",
            },
        ),
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "price",
                    models.BigIntegerField(default=0, verbose_name="Narxi"),
                ),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Holati"),
                ),
                (
                    "trans_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Tranzaksiya ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="payments.orders",
                        verbose_name="Buyurtma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payments",
                "verbose_name_plural": "Payments",
            },
        ),
        migrations.CreateModel(
            name="Plans",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqti"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Yangilangan vaqti"
                    ),
                ),
                (
                    "price",
                    models.BigIntegerField(default=0, verbose_name="Narxi"),
                ),
                (
                    "quarter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="classcom.quarter",
                        verbose_name="Chorak",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reja",
                "verbose_name_plural": "Rejalar",
            },
        ),
    ]
