# Generated by Django 5.0.1 on 2024-09-11 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("http", "0001_initial"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="class_type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="http.classgroup",
                verbose_name="Sinf turi",
            ),
            preserve_default=False,
        ),
    ]
