# Generated by Django 5.0.7 on 2024-08-06 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_orders"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="order",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.orders",
            ),
            preserve_default=False,
        ),
    ]
