# Generated by Django 5.0.7 on 2024-08-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0004_payments_created_at_payments_price_payments_trans_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="orders",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="start_date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
