# Generated by Django 5.1 on 2024-08-19 06:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "classcom",
            "0030_alter_answer_options_alter_category_options_and_more",
        ),
        (
            "payments",
            "0006_alter_orders_options_alter_payments_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orders",
            options={
                "verbose_name": "Buyurtmalar",
                "verbose_name_plural": "Buyurtmalar",
            },
        ),
        migrations.AlterModelOptions(
            name="plans",
            options={"verbose_name": "Reja", "verbose_name_plural": "Rejalar"},
        ),
        migrations.AddField(
            model_name="orders",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orders",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AddField(
            model_name="plans",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Yaratilgan vaqti",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="plans",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Tugash sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="price",
            field=models.BigIntegerField(default=0, verbose_name="Narxi"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="science",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.science",
                verbose_name="Fan",
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="start_date",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Boshlanish sanasi"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Holati"),
        ),
        migrations.AlterField(
            model_name="orders",
            name="types",
            field=models.ManyToManyField(
                to="classcom.sciencetypes", verbose_name="Fan turi"
            ),
        ),
        migrations.AlterField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Foydalanuvchi",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Yaratilgan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="payments.orders",
                verbose_name="Buyurtma",
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="price",
            field=models.BigIntegerField(default=0, verbose_name="Narxi"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="status",
            field=models.BooleanField(default=False, verbose_name="Holati"),
        ),
        migrations.AlterField(
            model_name="payments",
            name="trans_id",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Tranzaksiya ID"
            ),
        ),
        migrations.AlterField(
            model_name="payments",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Yangilangan vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="plans",
            name="price",
            field=models.BigIntegerField(default=0, verbose_name="Narxi"),
        ),
        migrations.AlterField(
            model_name="plans",
            name="quarter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="classcom.quarter",
                verbose_name="Chorak",
            ),
        ),
    ]
